management: 
  endpoint: 
    metrics: 
      enabled: true
    prometheus: 
      enabled: true
  endpoints: 
    web: 
      exposure: 
        include: "*"
  metrics: 
    export: 
      prometheus: 
        enabled: true
spring: 
  application: 
    name: csmt-biz-bureau-operation-2511
  jackson: 
    serialization: 
      WRITE_DATES_AS_TIMESTAMPS: false
  profiles: 
    active: local
  sleuth: 
    sampler: 
      percentage: 1
