apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.microservice.Name}}
  namespace: {{ .Values.microservice.namespace }}
  labels:
     app: {{ .Values.microservice.Name }}
     app.tool.name: DMB-DSB
data: 
  application.properties: |-
      spring.data.mongodb.host={{ .Values.microservice.dataSourceHost }}
      spring.data.mongodb.port={{ .Values.microservice.dataSourcePort }}
      spring.data.mongodb.database={{ .Values.microservice.database }}
  prometheus.yml: |- 
  
    - job_name: {{ .Values.microservice.Name}}
      scrape_interval: 5s
      metrics_path: '/actuator/prometheus'
      scheme: https
      static_configs:
      {{- range $host := .Values.ingress.hosts }}
        - targets:
            - {{ $host }}
      {{- end }}