apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.microservice.Name }}
    app.tool.name: DMB-DSB
  name: {{ .Values.microservice.Name }}
  namespace: {{ .Values.microservice.namespace }}
spec:
  ports:
  - name: {{ .Values.microservice.Name }}
    port: {{ .Values.microservice.containerport }}
    protocol: TCP
    targetPort: {{ .Values.microservice.containerport }} 
  selector:
    app: {{ .Values.microservice.Name }}
  sessionAffinity: None
  type: {{ .Values.microservice.type }}